version: '3.8'
services:
  db:
    image: 'postgres:15-alpine'
    container_name: postgres-user-service
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: userdbproject
    ports:
      - "5432:5432"
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    # networks:
    #   - mynet

  app:
    image: "user-service"
    build: 
      context: .
      # dockerfile: Dockerfile
    container_name: user-service-app
    ports:
      - "8083:8083"
    environment:
      # DB_HOST: db
      # DB_PORT: 5432
      # DB_NAME: userdbproject
      # DB_USERNAME: myuser
      # DB_PASSWORD: mypass
      # SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdbproject
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdbproject
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    depends_on:
      - db
    # networks:
    #   - mynet

# volumes:
#   db_data:

# networks:
#   mynet: